//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimedPower.Resources.langs {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
#pragma warning disable CS8981 // 该类型名称仅包含小写 ascii 字符。此类名称可能会成为该语言的保留值。
	internal class language {
#pragma warning restore CS8981 // 该类型名称仅包含小写 ascii 字符。此类名称可能会成为该语言的保留值。

		private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal language() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TimedPower.Resources.langs.language", typeof(language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string global_hibernate {
            get {
                return ResourceManager.GetString("global.hibernate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string global_reboot {
            get {
                return ResourceManager.GetString("global.reboot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string global_shutdown {
            get {
                return ResourceManager.GetString("global.shutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string global_sleep {
            get {
                return ResourceManager.GetString("global.sleep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string global_userlock {
            get {
                return ResourceManager.GetString("global.userlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string global_useroff {
            get {
                return ResourceManager.GetString("global.useroff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon image_logo_ico_window {
            get {
                object obj = ResourceManager.GetObject("image.logo.ico.window", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap image_logo_png_32x {
            get {
                object obj = ResourceManager.GetObject("image.logo.png.32x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string main_fileWindow_newTaskFile_filter {
            get {
                return ResourceManager.GetString("main.fileWindow.newTaskFile.filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string main_fileWindow_newTaskFile_title {
            get {
                return ResourceManager.GetString("main.fileWindow.newTaskFile.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string main_messagebox_checkUpdateFailed {
            get {
                return ResourceManager.GetString("main.messagebox.checkUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string main_messagebox_downloadDone {
            get {
                return ResourceManager.GetString("main.messagebox.downloadDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string main_messagebox_downloadUpdateFailed {
            get {
                return ResourceManager.GetString("main.messagebox.downloadUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string main_messagebox_haveUpdate {
            get {
                return ResourceManager.GetString("main.messagebox.haveUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string main_messagebox_isNewVersion {
            get {
                return ResourceManager.GetString("main.messagebox.isNewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string main_messagebox_littleTimeWarning {
            get {
                return ResourceManager.GetString("main.messagebox.littleTimeWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string main_messagebox_newVersionNeedRemoveOldVersionReg {
            get {
                return ResourceManager.GetString("main.messagebox.newVersionNeedRemoveOldVersionReg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string main_messagebox_onlyUseFuture {
            get {
                return ResourceManager.GetString("main.messagebox.onlyUseFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string main_messagebox_thanksToUse {
            get {
                return ResourceManager.GetString("main.messagebox.thanksToUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string main_messagebox_thanksToUse2 {
            get {
                return ResourceManager.GetString("main.messagebox.thanksToUse2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string main_messagebox_timeValueError {
            get {
                return ResourceManager.GetString("main.messagebox.timeValueError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string main_messagebox_timeValueTooBig {
            get {
                return ResourceManager.GetString("main.messagebox.timeValueTooBig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string main_winToast_timeWarning_autoTask_button {
            get {
                return ResourceManager.GetString("main.winToast.timeWarning_autoTask.button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string main_winToast_timeWarning_autoTask_text {
            get {
                return ResourceManager.GetString("main.winToast.timeWarning_autoTask.text", resourceCulture);
            }
        }
    }
}
