name: .NET Core Desktop

on:
  push:
    branches: ["github-action_dev"] #[ "main" ]
  pull_request:
    branches: ["github-action_dev"] #[ "main" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      with:
          lfs: true #启用lfs支持

    - name: Pull LFS files #拉取lfs中的实际文件
      run: git lfs pull
    
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core 8.0
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Publish build with 'FolderProfile'
      run: dotnet publish -p:PublishProfile=FolderProfile

    - name: Get version text #根据version.txt文件获取版本号
      shell: pwsh
      run: |
        $content = Get-Content -Path "${{ github.workspace }}\version.txt" -Raw
        echo "VERSION=$content" >> $env:GITHUB_ENV

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Release-V${{ env.VERSION }}
        path: ${{ github.workspace }}\TimedPower\bin\Release\net8.0-windows10.*\publish\**
